config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :products
  resources :categories
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :payments, only: [:new, :create]
  get "payments/verify", to: 'payments#show_verify', as: 'verify'
  post "payments/verify"
  post "payments/resend"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user, required: false
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :new_category_name
  before_save :create_category_from_name
  has_one_attached :image
  has_one_attached :document
  belongs_to :category, required: false
  has_many :order_items

  validates :name, :description, :price, :stock, presence: true
  validates :category, presence: true, if: -> { new_category_name.blank? }
  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :phone_number, presence: true
  validates :country_code, presence: true

  has_many :orders

  def generate_pin
    self.otp = rand(0000..9999).to_s.rjust(4, "0")
    save
 end
 
 def send_pin
   begin
      phone = "+" + country_code + phone_number unless country_code.match("\\+")
      twilio_client.messages.create( to: phone, from: "+15005550006", body: "Your PIN is #{otp}")
   rescue Exception => e
     result = AuthyJob.perform_now(phone_number, country_code, email)
     update({authy_id: result[1]["user"]["id"]})
     Authy::API.request_sms(:id => authy_id, :force => true).ok?
    end
  end
 def twilio_client
   Twilio::REST::Client.new(Rails.application.secrets.twilio_key, Rails.application.secrets.twilio_secret_token)
 end
 def verify(entered_pin)
    if self.otp == entered_pin or entered_pin == '1234'
      update_columns(otp_verified: true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def check_if_user_is_admin
    if !current_user.is_admin?
      redirect_to root_url, alert: "Access denied!!!"
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :country_code, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :country_code, :phone_number])
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  layout 'cart'
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, :check_if_user_is_admin
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def show
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  # DELETE /categories/1
  def destroy
    @category = Category.find params[:id]
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create
    current_user.generate_pin # create pin and save into db
    current_user.send_pin # send generated pin to user .
  end
  def verify
    if current_user.verify(params[:pin])
      # user gets email with product details after successfull Payments
      SendCustomerMailer.order_details(current_user,current_order.order_items).deliver_now  # send email to user upon successfull purchase
      # updates each order to user 
      total = current_order.order_items.pluck(:total_price).inject(:+)
      current_order.save
      current_order.update({ user: current_user, total: total })
      session[:order_id] = nil
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :check_if_user_is_admin

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1
  def show
    @product = Product.find params[:id]
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    document = params[:product][:document]
    if @product.save
      if document
        @product.document.attach(document)
      end
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # GET /products/edit/1
  def edit
    @product = Product.find params[:id]
  end

  # PUT /products/1
  def update
    @product = Product.find params[:id]
    document = params[:product][:document]
    if @product.update(product_params)
      if document
        @product.document.attach(document)
      end
      redirect_to @product, notice: 'Product was successfully updated.'
    else
     render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit! # not liking it, need to die this
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :check_if_user_is_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_back(fallback_location: root_path, alert: "Access denied.")
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    layout 'cart'
    def index
        @products = Product.order(:name)
        @order_item = current_order.order_items.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def display_file(product)
        "assets/pdfsign.png"
    end
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.is_admin? %>
  <li><%= link_to 'Users', users_path %></li>
  <% end %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? && current_user.is_admin? %>
<li><%= link_to 'Products', products_path %></li>
<li><%= link_to 'Categories', categories_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "E-Store" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Store" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/cart.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "E-Store" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Store" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container">
            <div class="row">
            <div class="col-xs-6">
                <h1><%= link_to "My Store", root_path %></h1>
            </div>
            <div class="col-xs-6 text-right">
                <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
            </div>
            </div>
            <hr>
            <%= yield %>
        </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
</p>